version: '3.8'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: nest_app_db
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'

  nestjs-app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - db
